#!/usr/bin/env bash

: ${SYSLOG_SERVER:="localhost"}
: ${SYSLOG_PORT:="514"}
: ${SYSLOG_TAG:="redtruck"}

log() {
  echo "<1>1 - $HOSTNAME $SYSLOG_TAG - - - $@" | nc -w 1 -u $SYSLOG_SERVER $SYSLOG_PORT
}
